---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_host: 127.0.0.1

  children:
    local:
      hosts:
        localhost:

    local_hosts:
      hosts:
        localhost:
