name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t ansible-role-test -f docker/Dockerfile .
      - name: Save Docker image
        run: docker save ansible-role-test -o image.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  test:
    name: Test Ansible Role
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      - name: Load Docker image
        run: docker load -i image.tar
      - name: Run role in container
        run: |
          docker run -d --name ansible-container ansible-role-test tail -f /dev/null