name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t ansible-role-test:latest .

    - name: Run Docker container
      run: |
        docker run --rm ansible-role-test:latest || { echo "Container failed to run"; exit 1; }
