name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Ansible Roles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install ansible ansible-lint yamllint
      - name: Run yamllint
        run: yamllint roles/
      - name: Run ansible-lint
        run: ansible-lint roles/

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t ansible-role-test:latest -f docker/Dockerfile .

  test:
    name: Run Role in Container
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run Container
        run: docker run --rm ansible-role-test:latest

  log_check:
    name: Check Logs
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt update && sudo apt install -y jq
      - name: Verify Log JSON
        run: |
          if [ ! -f /ansible/log.json ]; then
            echo "Log file not found!"
            exit 1
          fi
          jq empty /ansible/log.json
